name: main

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: node:20
    steps:
      - uses: actions/checkout@v4
      - name: npm install
        run: npm install
      - name: npm run build
        run: npm run build
    